# Generated by Django 2.1.4 on 2019-01-03 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('photo_name', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=200)),
                ('item_id', models.UUIDField(default=uuid.uuid4)),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
    ]
