# Generated by Django 2.1.4 on 2018-12-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='item_id',
            field=models.IntegerField(default=1),
        ),
    ]
