# Generated by Django 2.1.4 on 2018-12-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_photo_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item_id',
            field=models.IntegerField(default=38),
        ),
    ]
