# Generated by Django 2.1.4 on 2019-01-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181231_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item_id',
            field=models.IntegerField(default=50),
        ),
    ]
