# Generated by Django 2.1.4 on 2018-12-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181230_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AlterField(
            model_name='photo',
            name='item_id',
            field=models.IntegerField(default=15),
        ),
    ]
