# Generated by Django 2.1.4 on 2019-01-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190101_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item_id',
            field=models.IntegerField(default=21),
        ),
    ]
