# Generated by Django 2.1.4 on 2018-12-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181230_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='photo',
            name='item_id',
            field=models.IntegerField(default=6),
        ),
    ]
