# Generated by Django 2.1.4 on 2018-12-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181230_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item_id',
            field=models.IntegerField(default=3),
        ),
    ]
